server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://EUREKA:8080/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

ribbon:
  ServerListRefreshInterval: 5000
